BMO 1692910: Avoid the race between `set_volume` and stream-reinitialization (#122)
* Manual test: Add a command to set stream volume

* Test case - `assertion failed: !unit.is_null()` in `set_volume`

The following commit message demonstrating a possible cause of
the assertion-failed issue in [BMO 1692910](https://bugzilla.mozilla.org/show_bug.cgi?id=1692910)

This is a data-racing issue.  The assertion will be hit when the
1. `set_volume` is called on thread A at the same time when the stream is
   being reinitialized at thread B
2. `set_volume` is called on thread A just after the
   `self.core_stream_data.close()` is called on the thread B, which will
   uninitialize and dispose the AudioUnit called in `set_volume` on
   thread A

This commit adds some delay to give us a room to call the
`AudioUnitStream.set_volume` in the manual test, `test_stream_tester`,
after the `AudioUnitStream.stream.core_stream_data.close()` is called
when the `AudioUnitStream` is being reinitialized

The following log illustrates the steps to hit that assertion in
`AudioUnitStream.set_volume` on purpose:
```
% cargo test test_stream_tester -- --ignored --nocapture
   Compiling cubeb-coreaudio v0.1.0 (/Users/cchang/Work/cubeb-coreaudio-rs)
    Finished test [unoptimized + debuginfo] target(s) in 3.24s
     Running target/debug/deps/cubeb_coreaudio-29d6ac8d8020965d

running 1 test
commands:
	'q': quit
	'c': create a stream
	'd': destroy a stream
	's': start the created stream
	't': stop the created stream
	'r': register a device changed callback
	'v': set volume
c
Select stream type:
1) Input 2) Output 3) In-Out Duplex 4) Back
2
Stream 0x7f86967160f0 created.
commands:
	'q': quit
	'c': create a stream
	'd': destroy a stream
	's': start the created stream
	't': stop the created stream
	'r': register a device changed callback
	'v': set volume
s
state: Started
Stream 0x7f86967160f0 started.
commands:
	'q': quit
	'c': create a stream
	'd': destroy a stream
	's': start the created stream
	't': stop the created stream
	'r': register a device changed callback
	'v': set volume

*******************************************************************
* Switch the audio device here to trigger stream reinitializatoin *
*******************************************************************

1 Reinit > Sleep for 5s
v
thread 'backend::tests::manual::test_stream_tester' panicked at 'assertion failed: !unit.is_null()', src/backend/mod.rs:268:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test backend::tests::manual::test_stream_tester ... FAILED

failures:

failures:
    backend::tests::manual::test_stream_tester

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 182 filtered out
```

* Move `set_volume` to the task-queue running stream reinitialization

One simple way to avoid the data-racing issue mentioned in the previous
commit is to dispatch the `set_volume` task to the same task-queue that
runs the stream reinitialization tasks (it executes the stream
destroying task as well). That is, if `set_volume` task is executed
before stream reinitialization, the volume will be set before the stream
is reinitialized. If the `set_volume` task is executed after stream
reinitialization, the volume will be set after the stream finishes its
reinitialization task.

* Revert "Test case - `assertion failed: !unit.is_null()` in `set_volume`"

This reverts commit 8c1e3f91bd05643113d00ba93c965711f5ac3c10.

* Update README